In [1]:
#rutas de trabajo
from pathlib import Path
import pandas as pd
import numpy as np

BASE_DIR = Path("../")
DATOS = BASE_DIR / "datos"

DATOS.mkdir(parents=True, exist_ok=True)
print("Carpeta de datos:", DATOS)

Carpeta de datos: ..\datos

In [20]:
# Definir la ruta del archivo CSV
ruta_entrada = DATOS / "dataset_consolidado.csv"

# Cargar el dataset
df = pd.read_csv(ruta_entrada)

# Mostrar los primeros registros
df.head()

,registro_id,empleado_id,periodo,fecha_evaluacion,productividad_pct,calidad_trabajo_pct,cumplimiento_objetivos_pct,asistencia_pct,horas_capacitacion,horas_extra,...,fecha_encuesta,canal,comentario_abierto,sentimiento_declarado,anonimizada,respuestas_satisfaccion_laboral,respuestas_relacion_con_jefatura,respuestas_reconocimiento,respuestas_balance_vida_trabajo,respuestas_intencion_de_permanecer
0,1,EMP001,2025-Q3,2025-09-30,76.2,72.1,68.6,97.6,12,9,...,2026-06-04,Aplicación móvil,El ambiente es aceptable; espero más oportunid...,neutral,True,4,2,3,3,3
1,2,EMP001,2025-Q4,2025-12-31,56.2,76.7,71.5,94.1,11,12,...,2026-06-04,Aplicación móvil,El ambiente es aceptable; espero más oportunid...,neutral,True,4,2,3,3,3
2,3,EMP001,2026-Q1,2026-03-31,75.1,67.9,76.0,92.8,10,19,...,2026-06-04,Aplicación móvil,El ambiente es aceptable; espero más oportunid...,neutral,True,4,2,3,3,3
3,4,EMP001,2026-Q2,2026-06-30,71.6,79.8,78.1,93.3,9,8,...,2026-06-04,Aplicación móvil,El ambiente es aceptable; espero más oportunid...,neutral,True,4,2,3,3,3
4,5,EMP002,2025-Q3,2025-09-30,76.5,80.2,86.3,98.7,4,5,...,2026-06-07,Aplicación móvil,El ambiente laboral facilita mi productividad ...,positivo,True,5,5,5,3,5

In [21]:
#revisar dimensiones del dataset
print("Filas y columnas:", df.shape)
print("Cantidad de registros:", df.shape[0])
print("Cantidad de columnas:", df.shape[1])

Filas y columnas: (160, 36)
Cantidad de registros: 160
Cantidad de columnas: 36

In [22]:
#revisar tipos de datos de cada columna
print("Tipos de datos:")
print(df.dtypes)
print("\nInformación del dataset:")
df.info()

Tipos de datos:
registro_id                             int64
empleado_id                               str
periodo                                   str
fecha_evaluacion                          str
productividad_pct                     float64
calidad_trabajo_pct                   float64
cumplimiento_objetivos_pct            float64
asistencia_pct                        float64
horas_capacitacion                      int64
horas_extra                             int64
ausencias_dias                          int64
puntaje_desempeno                     float64
nivel_desempeno                           str
nombre_completo                           str
genero                                    str
edad                                    int64
fecha_ingreso                             str
salario_mensual                       float64
modalidad                                 str
estado_laboral                            str
fecha_salida                              str
puesto                                    str
nivel_puesto                              str
departamento                              str
ubicacion_departamento                    str
encuesta_id                               str
fecha_encuesta                            str
canal                                     str
comentario_abierto                        str
sentimiento_declarado                     str
anonimizada                              bool
respuestas_satisfaccion_laboral         int64
respuestas_relacion_con_jefatura        int64
respuestas_reconocimiento               int64
respuestas_balance_vida_trabajo         int64
respuestas_intencion_de_permanecer      int64
dtype: object

Información del dataset:
<class 'pandas.DataFrame'>
RangeIndex: 160 entries, 0 to 159
Data columns (total 36 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   registro_id                         160 non-null    int64
 1   empleado_id                         160 non-null    str
 2   periodo                             160 non-null    str
 3   fecha_evaluacion                    160 non-null    str
 4   productividad_pct                   160 non-null    float64
 5   calidad_trabajo_pct                 160 non-null    float64
 6   cumplimiento_objetivos_pct          160 non-null    float64
 7   asistencia_pct                      160 non-null    float64
 8   horas_capacitacion                  160 non-null    int64
 9   horas_extra                         160 non-null    int64
 10  ausencias_dias                      160 non-null    int64
 11  puntaje_desempeno                   160 non-null    float64
 12  nivel_desempeno                     160 non-null    str
 13  nombre_completo                     160 non-null    str
 14  genero                              160 non-null    str
 15  edad                                160 non-null    int64
 16  fecha_ingreso                       160 non-null    str
 17  salario_mensual                     160 non-null    float64
 18  modalidad                           160 non-null    str
 19  estado_laboral                      160 non-null    str
 20  fecha_salida                        24 non-null     str
 21  puesto                              160 non-null    str
 22  nivel_puesto                        160 non-null    str
 23  departamento                        160 non-null    str
 24  ubicacion_departamento              160 non-null    str
 25  encuesta_id                         160 non-null    str
 26  fecha_encuesta                      160 non-null    str
 27  canal                               160 non-null    str
 28  comentario_abierto                  160 non-null    str
 29  sentimiento_declarado               160 non-null    str
 30  anonimizada                         160 non-null    bool
 31  respuestas_satisfaccion_laboral     160 non-null    int64
 32  respuestas_relacion_con_jefatura    160 non-null    int64
 33  respuestas_reconocimiento           160 non-null    int64
 34  respuestas_balance_vida_trabajo     160 non-null    int64
 35  respuestas_intencion_de_permanecer  160 non-null    int64
dtypes: bool(1), float64(6), int64(10), str(19)
memory usage: 44.0 KB

In [23]:
#revisar valores nulos
reporte_nulos = pd.DataFrame({
    "cantidad_nulos": df.isnull().sum(),
    "porcentaje_nulos": (df.isnull().mean() * 100).round(2)
})

reporte_nulos

                                    cantidad_nulos  porcentaje_nulos
registro_id                                      0               0.0
empleado_id                                      0               0.0
periodo                                          0               0.0
fecha_evaluacion                                 0               0.0
productividad_pct                                0               0.0
calidad_trabajo_pct                              0               0.0
cumplimiento_objetivos_pct                       0               0.0
asistencia_pct                                   0               0.0
horas_capacitacion                               0               0.0
horas_extra                                      0               0.0
ausencias_dias                                   0               0.0
puntaje_desempeno                                0               0.0
nivel_desempeno                                  0               0.0
nombre_completo                                  0               0.0
genero                                           0               0.0
edad                                             0               0.0
fecha_ingreso                                    0               0.0
salario_mensual                                  0               0.0
modalidad                                        0               0.0
estado_laboral                                   0               0.0
fecha_salida                                   136              85.0
puesto                                           0               0.0
nivel_puesto                                     0               0.0
departamento                                     0               0.0
ubicacion_departamento                           0               0.0
encuesta_id                                      0               0.0
fecha_encuesta                                   0               0.0
canal                                            0               0.0
comentario_abierto                               0               0.0
sentimiento_declarado                            0               0.0
anonimizada                                      0               0.0
respuestas_satisfaccion_laboral                  0               0.0
respuestas_relacion_con_jefatura                 0               0.0
respuestas_reconocimiento                        0               0.0
respuestas_balance_vida_trabajo                  0               0.0
respuestas_intencion_de_permanecer               0               0.0

In [24]:
#revisar valores duplicados
duplicados = df.duplicated().sum()

print("Registros duplicados:", duplicados)
df[df.duplicated(keep=False)]

Registros duplicados: 0

Empty DataFrame
Columns: [registro_id, empleado_id, periodo, fecha_evaluacion, productividad_pct, calidad_trabajo_pct, cumplimiento_objetivos_pct, asistencia_pct, horas_capacitacion, horas_extra, ausencias_dias, puntaje_desempeno, nivel_desempeno, nombre_completo, genero, edad, fecha_ingreso, salario_mensual, modalidad, estado_laboral, fecha_salida, puesto, nivel_puesto, departamento, ubicacion_departamento, encuesta_id, fecha_encuesta, canal, comentario_abierto, sentimiento_declarado, anonimizada, respuestas_satisfaccion_laboral, respuestas_relacion_con_jefatura, respuestas_reconocimiento, respuestas_balance_vida_trabajo, respuestas_intencion_de_permanecer]
Index: []

[0 rows x 36 columns]

In [25]:
#normalizar nombres de columnas
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

df.columns

Index(['registro_id', 'empleado_id', 'periodo', 'fecha_evaluacion',
       'productividad_pct', 'calidad_trabajo_pct',
       'cumplimiento_objetivos_pct', 'asistencia_pct', 'horas_capacitacion',
       'horas_extra', 'ausencias_dias', 'puntaje_desempeno', 'nivel_desempeno',
       'nombre_completo', 'genero', 'edad', 'fecha_ingreso', 'salario_mensual',
       'modalidad', 'estado_laboral', 'fecha_salida', 'puesto', 'nivel_puesto',
       'departamento', 'ubicacion_departamento', 'encuesta_id',
       'fecha_encuesta', 'canal', 'comentario_abierto',
       'sentimiento_declarado', 'anonimizada',
       'respuestas_satisfaccion_laboral', 'respuestas_relacion_con_jefatura',
       'respuestas_reconocimiento', 'respuestas_balance_vida_trabajo',
       'respuestas_intencion_de_permanecer'],
      dtype='str')

In [26]:
#normalizar campos de texto
columnas_texto = df.select_dtypes(include="object").columns

for columna in columnas_texto:
    df[columna] = df[columna].astype("string").str.strip()
print(columnas_texto)
df.head()

Index(['empleado_id', 'periodo', 'fecha_evaluacion', 'nivel_desempeno',
       'nombre_completo', 'genero', 'fecha_ingreso', 'modalidad',
       'estado_laboral', 'fecha_salida', 'puesto', 'nivel_puesto',
       'departamento', 'ubicacion_departamento', 'encuesta_id',
       'fecha_encuesta', 'canal', 'comentario_abierto',
       'sentimiento_declarado'],
      dtype='str')

C:\Users\tatyp\AppData\Local\Temp\ipykernel_3900\3682146388.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  columnas_texto = df.select_dtypes(include="object").columns

,registro_id,empleado_id,periodo,fecha_evaluacion,productividad_pct,calidad_trabajo_pct,cumplimiento_objetivos_pct,asistencia_pct,horas_capacitacion,horas_extra,...,fecha_encuesta,canal,comentario_abierto,sentimiento_declarado,anonimizada,respuestas_satisfaccion_laboral,respuestas_relacion_con_jefatura,respuestas_reconocimiento,respuestas_balance_vida_trabajo,respuestas_intencion_de_permanecer
0,1,EMP001,2025-Q3,2025-09-30,76.2,72.1,68.6,97.6,12,9,...,2026-06-04,Aplicación móvil,El ambiente es aceptable; espero más oportunid...,neutral,True,4,2,3,3,3
1,2,EMP001,2025-Q4,2025-12-31,56.2,76.7,71.5,94.1,11,12,...,2026-06-04,Aplicación móvil,El ambiente es aceptable; espero más oportunid...,neutral,True,4,2,3,3,3
2,3,EMP001,2026-Q1,2026-03-31,75.1,67.9,76.0,92.8,10,19,...,2026-06-04,Aplicación móvil,El ambiente es aceptable; espero más oportunid...,neutral,True,4,2,3,3,3
3,4,EMP001,2026-Q2,2026-06-30,71.6,79.8,78.1,93.3,9,8,...,2026-06-04,Aplicación móvil,El ambiente es aceptable; espero más oportunid...,neutral,True,4,2,3,3,3
4,5,EMP002,2025-Q3,2025-09-30,76.5,80.2,86.3,98.7,4,5,...,2026-06-07,Aplicación móvil,El ambiente laboral facilita mi productividad ...,positivo,True,5,5,5,3,5

In [29]:
# Convertir columnas de fecha a tipo datetime

df["fecha_ingreso"] = pd.to_datetime(
    df["fecha_ingreso"],
    errors="coerce"
)

df["fecha_salida"] = pd.to_datetime(
    df["fecha_salida"],
    errors="coerce"
)

df["fecha_evaluacion"] = pd.to_datetime(
    df["fecha_evaluacion"],
    errors="coerce"
)

df["fecha_encuesta"] = pd.to_datetime(
    df["fecha_encuesta"],
    errors="coerce"
)

# Verificar los tipos de datos
print(
    df[
        [
            "fecha_ingreso",
            "fecha_salida",
            "fecha_evaluacion",
            "fecha_encuesta"
        ]
    ].dtypes
)

fecha_ingreso       datetime64[us]
fecha_salida        datetime64[us]
fecha_evaluacion    datetime64[us]
fecha_encuesta      datetime64[us]
dtype: object

In [31]:
#Corregir valores inválidos

# 1. Validar edad
# Las edades menores de 18 o mayores de 70 se consideran inválidas
df.loc[
    (df["edad"] < 18) | (df["edad"] > 70),
    "edad"
] = np.nan


# 2. Validar horas de capacitación
# No pueden existir cantidades negativas
df.loc[
    df["horas_capacitacion"] < 0,
    "horas_capacitacion"
] = np.nan


# 3. Validar ausencias
# Los días de ausencia no pueden ser negativos
df.loc[
    df["ausencias_dias"] < 0,
    "ausencias_dias"
] = np.nan


# 4. Validar puntaje de desempeño
# Se asume que el puntaje debe estar en un rango de 0 a 100
df.loc[
    (df["puntaje_desempeno"] < 0) |
    (df["puntaje_desempeno"] > 100),
    "puntaje_desempeno"
] = np.nan


# 5. Validar respuestas de encuesta
# La escala utilizada es de 1 a 5
columnas_encuesta = [
    "satisfaccion_laboral",
    "relacion_con_jefatura",
    "reconocimiento",
    "balance_vida_trabajo",
    "intencion_de_permanecer"
]

columnas_encuesta = [
    "respuestas_satisfaccion_laboral",
    "respuestas_relacion_con_jefatura",
    "respuestas_reconocimiento",
    "respuestas_balance_vida_trabajo",
    "respuestas_intencion_de_permanecer"
]

# Convertir valores fuera del rango 1-5 en valores nulos
for columna in columnas_encuesta:
    df.loc[
        (df[columna] < 1) | (df[columna] > 5),
        columna
    ] = np.nan


# 6. Validar fechas
# Una fecha de salida no debería ser anterior a la fecha de ingreso
df.loc[
    df["fecha_salida"] < df["fecha_ingreso"],
    "fecha_salida"
] = pd.NaT


# 7. Revisar cuántos valores nulos quedaron luego de corregir inválidos
print("Valores nulos después de corregir datos inválidos:")
print(df.isnull().sum())

Valores nulos después de corregir datos inválidos:
registro_id                             0
empleado_id                             0
periodo                                 0
fecha_evaluacion                        0
productividad_pct                       0
calidad_trabajo_pct                     0
cumplimiento_objetivos_pct              0
asistencia_pct                          0
horas_capacitacion                      0
horas_extra                             0
ausencias_dias                          0
puntaje_desempeno                       0
nivel_desempeno                         0
nombre_completo                         0
genero                                  0
edad                                    0
fecha_ingreso                           0
salario_mensual                         0
modalidad                               0
estado_laboral                          0
fecha_salida                          136
puesto                                  0
nivel_puesto                            0
departamento                            0
ubicacion_departamento                  0
encuesta_id                             0
fecha_encuesta                          0
canal                                   0
comentario_abierto                      0
sentimiento_declarado                   0
anonimizada                             0
respuestas_satisfaccion_laboral         0
respuestas_relacion_con_jefatura        0
respuestas_reconocimiento               0
respuestas_balance_vida_trabajo         0
respuestas_intencion_de_permanecer      0
dtype: int64

In [32]:
#Tratamiento de valores nulos
# Revisar nuevamente la cantidad de valores nulos por columna
print("Valores nulos antes del tratamiento:")
print(df.isnull().sum())


# La columna fecha_salida puede contener valores nulos de forma válida.
# Un valor nulo indica que el colaborador aún no ha salido de la organización.
# Por esta razón, estos valores no serán reemplazados.

print("\nValores nulos en fecha_salida:")
print(df["fecha_salida"].isnull().sum())


# Verificar si existen valores nulos en las demás columnas
columnas_sin_fecha_salida = df.columns.drop("fecha_salida")

print("\nValores nulos en las demás columnas:")
print(df[columnas_sin_fecha_salida].isnull().sum())

Valores nulos antes del tratamiento:
registro_id                             0
empleado_id                             0
periodo                                 0
fecha_evaluacion                        0
productividad_pct                       0
calidad_trabajo_pct                     0
cumplimiento_objetivos_pct              0
asistencia_pct                          0
horas_capacitacion                      0
horas_extra                             0
ausencias_dias                          0
puntaje_desempeno                       0
nivel_desempeno                         0
nombre_completo                         0
genero                                  0
edad                                    0
fecha_ingreso                           0
salario_mensual                         0
modalidad                               0
estado_laboral                          0
fecha_salida                          136
puesto                                  0
nivel_puesto                            0
departamento                            0
ubicacion_departamento                  0
encuesta_id                             0
fecha_encuesta                          0
canal                                   0
comentario_abierto                      0
sentimiento_declarado                   0
anonimizada                             0
respuestas_satisfaccion_laboral         0
respuestas_relacion_con_jefatura        0
respuestas_reconocimiento               0
respuestas_balance_vida_trabajo         0
respuestas_intencion_de_permanecer      0
dtype: int64

Valores nulos en fecha_salida:
136

Valores nulos en las demás columnas:
registro_id                           0
empleado_id                           0
periodo                               0
fecha_evaluacion                      0
productividad_pct                     0
calidad_trabajo_pct                   0
cumplimiento_objetivos_pct            0
asistencia_pct                        0
horas_capacitacion                    0
horas_extra                           0
ausencias_dias                        0
puntaje_desempeno                     0
nivel_desempeno                       0
nombre_completo                       0
genero                                0
edad                                  0
fecha_ingreso                         0
salario_mensual                       0
modalidad                             0
estado_laboral                        0
puesto                                0
nivel_puesto                          0
departamento                          0
ubicacion_departamento                0
encuesta_id                           0
fecha_encuesta                        0
canal                                 0
comentario_abierto                    0
sentimiento_declarado                 0
anonimizada                           0
respuestas_satisfaccion_laboral       0
respuestas_relacion_con_jefatura      0
respuestas_reconocimiento             0
respuestas_balance_vida_trabajo       0
respuestas_intencion_de_permanecer    0
dtype: int64

In [33]:
#Eliminar registros duplicados

# Contar registros duplicados antes de eliminarlos
duplicados_antes = df.duplicated().sum()

print("Registros duplicados antes de limpiar:", duplicados_antes)


# Eliminar registros duplicados
df = df.drop_duplicates()


# Verificar el nuevo tamaño del dataset
print("Nuevo tamaño del dataset:", df.shape)


# Comprobar que ya no existan registros duplicados
duplicados_despues = df.duplicated().sum()

print("Registros duplicados después de limpiar:", duplicados_despues)

Registros duplicados antes de limpiar: 0
Nuevo tamaño del dataset: (160, 36)
Registros duplicados después de limpiar: 0

In [35]:
# Crear característica: antiguedad
# Representa la cantidad de años completos que el colaborador
# lleva trabajando en la organización

fecha_referencia = pd.Timestamp("2026-08-09")

df["antiguedad"] = (
    fecha_referencia.year - df["fecha_ingreso"].dt.year
)

# Restar un año si todavía no ha cumplido su aniversario laboral
df["antiguedad"] = df["antiguedad"] - (
    (fecha_referencia.month < df["fecha_ingreso"].dt.month) |
    (
        (fecha_referencia.month == df["fecha_ingreso"].dt.month) &
        (fecha_referencia.day < df["fecha_ingreso"].dt.day)
    )
)

# Verificar resultados
df[["fecha_ingreso", "antiguedad"]].head()

  fecha_ingreso  antiguedad
0    2022-09-17           3
1    2022-09-17           3
2    2022-09-17           3
3    2022-09-17           3
4    2025-07-26           1

In [36]:
# Crear característica: capacitaciones_recibidas
# Se estima una capacitación por cada 8 horas de formación registradas

df["capacitaciones_recibidas"] = (
    df["horas_capacitacion"] / 8
).round().astype("Int64")

# Verificar resultados
df[
    [
        "horas_capacitacion",
        "capacitaciones_recibidas"
    ]
].head()

   horas_capacitacion  capacitaciones_recibidas
0                12.0                         2
1                11.0                         1
2                10.0                         1
3                 9.0                         1
4                 4.0                         0

In [37]:
# Crear característica: nivel_desempeno_calculado
# Clasifica el puntaje de desempeño en Bajo, Medio o Alto

def clasificar_desempeno(puntaje):
    if puntaje < 60:
        return "Bajo"
    elif puntaje < 80:
        return "Medio"
    else:
        return "Alto"


df["nivel_desempeno_calculado"] = (
    df["puntaje_desempeno"].apply(clasificar_desempeno)
)

# Verificar resultados
df[
    [
        "puntaje_desempeno",
        "nivel_desempeno_calculado"
    ]
].head()

   puntaje_desempeno nivel_desempeno_calculado
0              77.55                     Medio
1              72.73                     Medio
2              77.06                     Medio
3              79.61                     Medio
4              84.31                      Alto

In [38]:
# Crear característica: riesgo_rotacion
# Se calcula utilizando satisfacción laboral, intención de permanecer
# y cantidad de días de ausencia

def calcular_riesgo_rotacion(fila):

    puntuacion_riesgo = 0

    # Baja intención de permanecer aumenta el riesgo
    if fila["respuestas_intencion_de_permanecer"] <= 2:
        puntuacion_riesgo += 2
    elif fila["respuestas_intencion_de_permanecer"] == 3:
        puntuacion_riesgo += 1

    # Baja satisfacción laboral aumenta el riesgo
    if fila["respuestas_satisfaccion_laboral"] <= 2:
        puntuacion_riesgo += 2
    elif fila["respuestas_satisfaccion_laboral"] == 3:
        puntuacion_riesgo += 1

    # Muchas ausencias pueden aumentar el riesgo
    if fila["ausencias_dias"] >= 8:
        puntuacion_riesgo += 2
    elif fila["ausencias_dias"] >= 4:
        puntuacion_riesgo += 1

    # Clasificar el riesgo obtenido
    if puntuacion_riesgo >= 4:
        return "Alto"
    elif puntuacion_riesgo >= 2:
        return "Medio"
    else:
        return "Bajo"


df["riesgo_rotacion"] = df.apply(
    calcular_riesgo_rotacion,
    axis=1
)

# Verificar resultados
df[
    [
        "respuestas_satisfaccion_laboral",
        "respuestas_intencion_de_permanecer",
        "ausencias_dias",
        "riesgo_rotacion"
    ]
].head()

,respuestas_satisfaccion_laboral,respuestas_intencion_de_permanecer,ausencias_dias,riesgo_rotacion
0,4.0,3.0,1.0,Bajo
1,4.0,3.0,3.0,Bajo
2,4.0,3.0,4.0,Medio
3,4.0,3.0,4.0,Medio
4,5.0,5.0,1.0,Bajo

In [39]:
# Crear característica: estado_colaborador
# Si existe fecha de salida o el estado laboral indica salida,
# el colaborador se considera inactivo

def determinar_estado_colaborador(fila):

    # Si tiene fecha de salida registrada
    if pd.notna(fila["fecha_salida"]):
        return "Inactivo"

    # Si continúa laboralmente activo
    if str(fila["estado_laboral"]).strip().lower() == "activo":
        return "Activo"

    # Para cualquier otro estado laboral
    return "Inactivo"


df["estado_colaborador"] = df.apply(
    determinar_estado_colaborador,
    axis=1
)

# Verificar resultados
df[
    [
        "estado_laboral",
        "fecha_salida",
        "estado_colaborador"
    ]
].head()

  estado_laboral fecha_salida estado_colaborador
0         Activo          NaT             Activo
1         Activo          NaT             Activo
2         Activo          NaT             Activo
3         Activo          NaT             Activo
4         Activo          NaT             Activo

In [40]:
# Visualizar las nuevas características creadas

df[
    [
        "antiguedad",
        "capacitaciones_recibidas",
        "nivel_desempeno_calculado",
        "riesgo_rotacion",
        "estado_colaborador"
    ]
].head(10)

,antiguedad,capacitaciones_recibidas,nivel_desempeno_calculado,riesgo_rotacion,estado_colaborador
0,3,2,Medio,Bajo,Activo
1,3,1,Medio,Bajo,Activo
2,3,1,Medio,Medio,Activo
3,3,1,Medio,Medio,Activo
4,1,0,Alto,Bajo,Activo
5,1,2,Alto,Bajo,Activo
6,1,1,Medio,Bajo,Activo
7,1,2,Alto,Bajo,Activo
8,2,2,Medio,Bajo,Activo
9,2,1,Medio,Bajo,Activo

In [41]:
# Generar reporte de calidad del dataset

# Crear un resumen general de calidad
reporte_calidad = pd.DataFrame({
    "columna": df.columns,
    "tipo_dato": df.dtypes.astype(str).values,
    "valores_nulos": df.isnull().sum().values,
    "porcentaje_nulos": (df.isnull().mean() * 100).round(2).values,
    "valores_unicos": df.nunique().values
})

# Mostrar el reporte
reporte_calidad
# Resumen general del dataset

print("Cantidad de registros:", df.shape[0])
print("Cantidad de columnas:", df.shape[1])
print("Total de valores nulos:", df.isnull().sum().sum())
print("Total de registros duplicados:", df.duplicated().sum())

Cantidad de registros: 160
Cantidad de columnas: 41
Total de valores nulos: 136
Total de registros duplicados: 0

In [42]:
# Paso 18. Guardar dataset limpio del proyecto

# Definir la ruta de salida
ruta_salida = DATOS / "dataset_limpio_guia02.csv"

# Guardar el DataFrame limpio en formato CSV
df.to_csv(
    ruta_salida,
    index=False,
    encoding="utf-8"
)

# Confirmar la ubicación del archivo generado
print("Dataset limpio guardado en:")
print(ruta_salida)

Dataset limpio guardado en:
..\datos\dataset_limpio_guia02.csv